### ISSUE TITLE
Pulling in Krypton commits to Leia

### ISSUE THREAD

**Issue by MadMikeDoc** [mikesilvo164/skin.aeon.madnox#26] opened 2017-04-11 06:55 UTC
Hi,

So, is there an easy way to pull in commits done to Krypton since the branch was created other than doing them all manually? I'm not up on PR's and all that and what happens if a file has already changed in Leia, does it merge the files or what?

Any comments / help would be greatfull, thanks.

Mike.

**Comment by mistervee** [comment] 2017-04-12 00:59
Done.
https://github.com/mikesilvo164/skin.aeon.madnox/pull/27

This could be an issue though in the future with work i am doing on the skin.

It's probably a good time to get your thoughts on other stuff that i am playing around with atm. If my suggestions are accepted a simple merge will be not possible.

In working on the resource integration i have become a bit side tracked on other parts of the skin due to finding other ways of reducing the size.
- area colors and variables
- media menu
- topbar
- unused or multiple textures that are so similar they are not required.
- fonts
- code bloat
- hard to maintain and inefficient code

The last two mentioned originate from the old versions of aeon and nox 4. Everything has been built around  6+ year old coding methods. Which does make coding and adding new features difficult and bugs are very easily introduced.

I am reworking the myweather xml as a trial. If it all works out nicely this can be integrated through out the skin rather easily. I will upload it to my branch when complete.

@MadMikeDoc @mikesilvo164 @bartolomesoriano @meowmoo 

Is this something you would be interested in and are you happy with this only being for Leia?

**Comment by MadMikeDoc** [comment] 2017-04-12 09:48
@mistervee , thanks for the PR I looked into it yesterday but don't really know what happens to Leia only changes if you pull again from Kpryton.

I'm still doing Krypton work as it's the latest released version but I think I'll look at applying the changes manually in Leia once all done for Krypton, might take time but probably the best way to update Leai with Krypton changes due to the on-going Leia only work

@meowmoo, can you look at applying any future Krypton changes in Leia branch as well please, otherwise give me aheads up and I'll try and manage it.

I like the ideas you have suggested and apologies as a lot of the code bloat etc is probably down to me as I learnt enough to be able to do ok skinning but for various reasons never took it further i.e. params.

So I'm interested in it and ok with it being for Leia only and just let me know if I can help?

Mike.

**Comment by mistervee** [comment] 2017-04-12 19:22
@MadMikeDoc 

No need to apologize for code bloat. Before this i was looking at the code for the original aeon and nox 4. The issue is a lot of the code remains from many years ago and that is the main culprit. The skinning engine in kodi has come a long way since then and the legacy code has never been improved upon apart from the rework of the main menu and widgets.

Your help will be great, will let you know soon. Just a warning, the use of Param includes is big part in the update. Once you get your head around how they work it will make skinning so much easier. Any help you need in understanding please ask.

**Comment by mistervee** [comment] 2017-04-21 23:45
@MadMikeDoc @bartolomesoriano @meowmoo 

See this post
https://github.com/mistervee/skin.aeon.madnox/issues/1

Updated a few things on my branch.

**Comment by mikesilvo164** [comment] 2018-01-15 23:38
Closing to only have new issues.  Please make a new one if this is still a problem.

Thanks.

**Closed by mikesilvo164** 2018-01-15 23:38 UTC
